name: asroo_store
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  connectivity_plus: ^6.0.3

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.0
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3

flutter_launcher_icons:
  image_path: 'assets/icons/app_icon.jpg'
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#000000"
  android_icon_foreground: "assets/icons/circle_icon.png"

dev_dependencies:
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/core/
    - lang/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 400
